Controllers/FoodModsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCarbonFootprintCalculator.Data;
using MyCarbonFootprintCalculator.Models;

namespace MyCarbonFootprintCalculator.Controllers
{
    public class FoodModsController : Controller
    {
        private readonly MyCarbonFootprintCalculatorContext _context;

        public FoodModsController(MyCarbonFootprintCalculatorContext context)
        {
            _context = context;
        }

        // GET: FoodMods
        public async Task<IActionResult> Index()
        {
            return View(await _context.Food.ToListAsync());
        }

        // GET: FoodMods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodMod = await _context.Food
                .FirstOrDefaultAsync(m => m.DietId == id);
            if (foodMod == null)
            {
                return NotFound();
            }

            return View(foodMod);
        }

        // GET: FoodMods/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FoodMods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DietId,DietType,Grains,Meat,Vegetables,Fruits,Fish,Milk,Desserts,Fast_foods")] FoodMod foodMod)
        {
            var total = foodMod.Grains + foodMod.Meat + foodMod.Vegetables + foodMod.Fruits + foodMod.Fish + foodMod.Milk + foodMod.Desserts + foodMod.Fast_foods;

            if (ModelState.IsValid && total == 100)
            {
                _context.Add(foodMod);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "FootprintMods");
            }
            ViewBag.errormessage = "Total percentages not equal to 100%";
            return View(foodMod);
        }

        // GET: FoodMods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodMod = await _context.Food.FindAsync(id);
            if (foodMod == null)
            {
                return NotFound();
            }
            return View(foodMod);
        }

        // POST: FoodMods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DietId,DietType,Grains,Meat,Vegetables,Fruits,Fish,Milk,Desserts,Fast_foods")] FoodMod foodMod)
        {
            var total = foodMod.Grains + foodMod.Meat + foodMod.Vegetables + foodMod.Fruits + foodMod.Fish + foodMod.Milk + foodMod.Desserts + foodMod.Fast_foods;
            if (id != foodMod.DietId)
            {
                return NotFound();
            }

            if (ModelState.IsValid && total == 100)
            {
                try
                {
                    _context.Update(foodMod);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodModExists(foodMod.DietId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.errormessage = "Total percentages not equal to 100%";
            return View(foodMod);
        }

        // GET: FoodMods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodMod = await _context.Food
                .FirstOrDefaultAsync(m => m.DietId == id);
            if (foodMod == null)
            {
                return NotFound();
            }

            return View(foodMod);
        }

        // POST: FoodMods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foodMod = await _context.Food.FindAsync(id);
            _context.Food.Remove(foodMod);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodModExists(int id)
        {
            return _context.Food.Any(e => e.DietId == id);
        }
    }
}

Controllers/GenInfoModsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCarbonFootprintCalculator.Data;
using MyCarbonFootprintCalculator.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace MyCarbonFootprintCalculator.Controllers
{
    public class GenInfoModsController : Controller
    {
        private readonly MyCarbonFootprintCalculatorContext _context;
        private readonly AuthDbContext _users;
        Location getlocation = new Location();

        public GenInfoModsController(MyCarbonFootprintCalculatorContext context, AuthDbContext user)
        {
            _context = context;
            _users = user;
        }

        // GET: GenInfoMods
        public async Task<IActionResult> Index()
        {
            return View(await _context.GenInfo.ToListAsync());
        }

        // GET: GenInfoMods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genInfoMod = await _context.GenInfo
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (genInfoMod == null)
            {
                return NotFound();
            }

            return View(genInfoMod);
        }

        // GET: GenInfoMods/Create
        public IActionResult Create()
        {
            var getID = new GenInfoMod();
            ViewBag.message = getID.UserId;
            ViewBag.currentUser = User.FindFirstValue(ClaimTypes.Name);
            return View();
        }

        // POST: GenInfoMods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,City,State,ZipCode,AnnualIncome")] GenInfoMod genInfoMod)
        {
            getlocation = await Location.Lookup(genInfoMod.ZipCode);

            genInfoMod.City = getlocation.City;
            genInfoMod.State = getlocation.State;
            genInfoMod.ZipCode = getlocation.Zip;
            if (ModelState.IsValid)
            {
                _context.Add(genInfoMod);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "HouseMods");
            }
            return View(genInfoMod);
        }

        // GET: GenInfoMods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genInfoMod = await _context.GenInfo.FindAsync(id);
            if (genInfoMod == null)
            {
                return NotFound();
            }
            return View(genInfoMod);
        }

        // POST: GenInfoMods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,City,State,ZipCode,AnnualIncome")] GenInfoMod genInfoMod)
        {
            if (id != genInfoMod.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genInfoMod);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenInfoModExists(genInfoMod.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genInfoMod);
        }

        // GET: GenInfoMods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genInfoMod = await _context.GenInfo
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (genInfoMod == null)
            {
                return NotFound();
            }

            return View(genInfoMod);
        }

        // POST: GenInfoMods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genInfoMod = await _context.GenInfo.FindAsync(id);
            _context.GenInfo.Remove(genInfoMod);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenInfoModExists(int id)
        {
            return _context.GenInfo.Any(e => e.UserId == id);
        }
    }
}

Controllers/HouseModsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCarbonFootprintCalculator.Data;
using MyCarbonFootprintCalculator.Models;

namespace MyCarbonFootprintCalculator.Controllers
{
    public class HouseModsController : Controller
    {
        private readonly MyCarbonFootprintCalculatorContext _context;

        public HouseModsController(MyCarbonFootprintCalculatorContext context)
        {
            _context = context;
        }

        // GET: HouseMods
        public async Task<IActionResult> Index()
        {
            return View(await _context.House.ToListAsync());
        }

        // GET: HouseMods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseMod = await _context.House
                .FirstOrDefaultAsync(m => m.HouseId == id);
            if (houseMod == null)
            {
                return NotFound();
            }

            return View(houseMod);
        }

        // GET: HouseMods/Create
        public IActionResult Create()=> View("Create", new HouseMod() { } );       

        // POST: HouseMods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HouseId,Size,Sqft,Energy_Usage,Energy_Type,Solar,Gas,Electric")] HouseMod houseMod)
        {
            if (ModelState.IsValid)
            {
                _context.Add(houseMod);
                houseMod.Energy_Type = GetEnergyType(houseMod.Solar, houseMod.Gas, houseMod.Electric);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "VehicleMods");
            }
            return View(houseMod);
        }

        // GET: HouseMods/Edit/5
        //[Route("HouseMods/Admin/Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseMod = await _context.House.FindAsync(id);
            if (houseMod == null)
            {
                return NotFound();
            }
            return View(houseMod);
        }

        // POST: HouseMods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HouseId,Size,Sqft,Energy_Usage,Energy_Type,Solar,Gas,Electric")] HouseMod houseMod)
        {
            if (id != houseMod.HouseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(houseMod);
                    houseMod.Energy_Type = GetEnergyType(houseMod.Solar, houseMod.Gas, houseMod.Electric); houseMod.Energy_Type = GetEnergyType(houseMod.Solar, houseMod.Gas, houseMod.Electric);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HouseModExists(houseMod.HouseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(houseMod);
        }

        // GET: HouseMods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseMod = await _context.House
                .FirstOrDefaultAsync(m => m.HouseId == id);
            if (houseMod == null)
            {
                return NotFound();
            }

            return View(houseMod);
        }

        // POST: HouseMods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var houseMod = await _context.House.FindAsync(id);
            _context.House.Remove(houseMod);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HouseModExists(int id)
        {
            return _context.House.Any(e => e.HouseId == id);
        }
        public string GetEnergyType(bool Solar, bool Gas, bool Electric)
        {
            var Energy_Type = "";
            if (Solar && !Gas && !Electric)
            {
                Energy_Type = "Solar";
            }
            else if (!Solar && Gas && !Electric)
            {
                Energy_Type = "Gas";
            }
            else if (!Solar && !Gas && Electric)
            {
                Energy_Type = "Electric";
            }
            else if (Solar && Gas && !Electric)
            {
                Energy_Type = "Solar and Gas";
            }
            else if (Solar && !Gas && Electric)
            {
                Energy_Type = "Solar and Electric";
            }
            else if (!Solar && Gas && Electric)
            {
                Energy_Type = "Gas and Electric";
            }
            else if (Solar && Gas && Electric)
            {
                Energy_Type = "Solar, Gas, and Electric";
            }
            else if (!Solar && !Gas && !Electric)
            {
                Energy_Type = "No value";
            }

            return Energy_Type;
        }
    }
}

Controllers/UserPageController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCarbonFootprintCalculator.Controllers
{
    public class UserPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Home()
        {
            return View();
        }
        public IActionResult General(int ID = 0, string name = "Guest")
        {
            ViewData["Message1"] = "ID " + ID;
            ViewData["Message"] = "Welcome " + name; 
            return View();
        }
        public IActionResult House()
        {
            return View();
        }
        public IActionResult Vehicles()
        {
            return View();
        }
        public IActionResult Food()
        {
            return View();
        }
        public IActionResult Footprint()
        {
            return View();
        }
    }
}

Views/FoodMods/Create.cshtml
@model MyCarbonFootprintCalculator.Models.FoodMod

@{
    ViewData["Title"] = "Create";
}

<h4>Diet Data</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <p style="color:red; font-weight:bold">@ViewBag.errormessage </p>
            <div class="form-group">
                <label asp-for="DietType" class="control-label">Diet Type</label>
                <select class="form-control" asp-for="DietType">
                    <option value="null"> Select your diet type</option>
                    <option value="Omnivore"> Omnivore</option>
                    <option value="Pescatarian"> Pescatarian</option>
                    <option value="Vegan"> Vegan</option>
                    <option value="Vegetarian"> Vegetarian</option>
                    <option value="Other"> Other</option>
                </select>
                <span asp-validation-for="DietType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grains" class="control-label"></label>
                @*<input asp-for="Grains" class="form-control" />*@
                <select class="form-control" asp-for="Grains">
                    <option value="null"> Select grains percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Grains" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Meat" class="control-label"></label>
                <select class="form-control" asp-for="Meat">
                    <option value="null"> Select meat percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Meat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vegetables" class="control-label"></label>
                <select class="form-control" asp-for="Vegetables">
                    <option value="null"> Select vegetables percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Vegetables" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fruits" class="control-label"></label>
                <select class="form-control" asp-for="Fruits">
                    <option value="null"> Select fruits percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Fruits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fish" class="control-label"></label>
                <select class="form-control" asp-for="Fish">
                    <option value="null"> Select fish percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Fish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Milk" class="control-label"></label>
                <select class="form-control" asp-for="Milk">
                    <option value="null"> Select milk percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Milk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desserts" class="control-label"></label>
                <select class="form-control" asp-for="Desserts">
                    <option value="null"> Select dessert percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Desserts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fast_foods" class="control-label">Fast food</label>
                <select class="form-control" asp-for="Fast_foods">
                    <option value="null"> Select fast food percentage</option>
                    @for (int i = 0; i <= 100; i += 10)
                    {
                        <option value="@i"> @i %</option>
                    }
                </select>
                <span asp-validation-for="Fast_foods" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Get Your Footprint >" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FoodMods/Details.cshtml
@model MyCarbonFootprintCalculator.Models.FoodMod

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FoodMod</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DietType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DietType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grains)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grains)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Meat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Meat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vegetables)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vegetables)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fruits)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fruits)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fish)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fish)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Milk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Milk)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desserts)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desserts)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fast_foods)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fast_foods)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DietId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/FoodMods/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCarbonFootprintCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/tabsedit.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    @RenderSection("link1", false)
</head>
<body>
    <header class="main-header">
        <h1>My Carbon FootPrint Calculator</h1>
    </header>
    <nav class="navbar navbar-expand" style="background-color:lightgoldenrodyellow">
        <div class="container">
            <ul class=" navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" style="padding-right:65px; padding-left:65px" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                </li>
                <li class="nav-item current">
                    <a class="nav-link text-dark" style="padding-right:65px; padding-left:65px" asp-area="" asp-controller="GenInfoMods" asp-action="Create">USER</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" style="padding-right:65px; padding-left:65px" asp-area="" asp-controller="HouseMods" asp-action="Create">HOUSE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" style="padding-right:65px; padding-left:65px" asp-area="" asp-controller="VehicleMods" asp-action="Create">VEHICLES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" style="padding-right:65px; padding-left:65px" asp-area="" asp-controller="FoodMods" asp-action="Create">FOOD</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" style="padding-right:65px; padding-left:65px" asp-area="" asp-controller="UserPage" asp-action="Footprint">FOOTPRINT</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyCarbonFootprintCalculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>